name: Deploy Backend Service

on:
  push:
    paths:
      - 'newBBYCweb/server/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: newBBYCweb/server/package.json

      - name: Install Dependencies
        working-directory: newBBYCweb/server
        run: npm ci

      - name: Build Application
        working-directory: newBBYCweb/server
        run: npm run build --if-present

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: newBBYCweb/server
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bbyc-server:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # 停止并删除旧容器
            docker stop bbyc-server || true
            docker rm bbyc-server || true
            
            # 拉取最新镜像
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/bbyc-server:latest
            
            # 创建网络（如果不存在）
            docker network create bbyc-network || true
            
            # 运行新容器
            docker run -d \
              --name bbyc-server \
              --network bbyc-network \
              -p 3000:3000 \
              -e MONGODB_URI=${{ secrets.MONGODB_URI }} \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              -e JWT_EXPIRE=30d \
              ${{ secrets.DOCKERHUB_USERNAME }}/bbyc-server:latest
            
            # 清理未使用的镜像
            docker image prune -f 